language: python

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4

install:
- sudo apt-get install telnet
- pip install 'pip>=6' 'setuptools>=12'
- pip install -r dev-requirements.txt

script: 
- flake8 --version
- flake8 c2c --max-line-length=100
- python setup.py nosetests

after_success:
- pip install coveralls
- coveralls
